### ISSUE TITLE
Rationalize options for sc_create.py

### ISSUE THREAD

**Issue by JoanneBogart** [LSSTDESC/skyCatalogs#117]
Several changes should be considered:

- [x] Have a separate option for object type rather than `no_galaxy`, `no_pointsource`, `sso`. Value would be a list though for normal (non-debugging) calls it would have a single element
- [ ] Have a separate option for files to be generated rather than `no_flux` and `no_main`. Value would be a list though mostly it would only have one element.  
- [x] Instead of previous item, split creation into two scripts, one for main files and one for flux files.
- [x] Eliminate `sed_subdir` option.  This is only used when writing out an instance catalog, a facility which is essentially broken
- [x] Add option `star_truth` so it is possible to use something other than default for value of `star_input_format`
- [x] Either rename `galaxy_stride` to just `stride` or add option `star_stride`

**Comment by JoanneBogart** [comment]
@jchiang87 do you have any comments about any of these?   Is there anything more that belongs on this list?

**Comment by jchiang87** [comment]
As far as the options themselves are concerned, I don't have any additional comments.  However, even though this is outside the scope of just changing the options, I'd recommend splitting the flux file generation off as an entirely separate application, since that really only depends on the main files, and I would think that most of the options would end up being irrelevant in this case.

**Comment by JoanneBogart** [comment]
Addressed by PR #120
